foreach(file IN ITEMS "include" "CMakeLists.txt" "LICENSE")
  cmake_path(ABSOLUTE_PATH file BASE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.." NORMALIZE)
  if(IS_DIRECTORY "${file}")
    file(GLOB_RECURSE sources "${file}/*")
    list(APPEND VCPKG_HASH_ADDITIONAL_FILES "${sources}")
  else()
    list(APPEND VCPKG_HASH_ADDITIONAL_FILES "${file}")
  endif()
endforeach()
